apiVersion: batch/v1
kind: CronJob

metadata:
  name: python-etl-cronjob
  namespace: python-etl

spec:
  schedule: "0 * * * *"

  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: python-etl
              image: tahacansiz/python-etl:latest

          restartPolicy: OnFailure